<?php

/**
 *  SFW - SimpleFrameWork
 *
 *  Copyright (C) 2013  Stefan Paproth
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program. If not, see
 *  http://www.gnu.org/licenses/agpl.txt.
 *
 */

?>

<div class="py-md-4 mx-auto" style="width: 35rem; padding-top: 3.5rem !important;">
    <div class="card card-block" style="padding: .75rem 1.25rem; border: .0625rem solid #c6c8ca; background-color: #d6d8d9">
        <h3 style="margin-bottom: 1.5rem;">Passwort rücksetzen</h3>


        <p>
            Bestätigungsnachricht wurde erfolgreich an
            <strong><?php echo($this->name); ?></strong>
            verschickt.
        </p>
        <p>
            Bitte klicke auf den Bestätigungslink den Du per E-Mail erhälst
            um Dein neues Passwort eingeben zu können.
        </p>
        <div class="alert alert-warning" role="alert">
            Der Bestätigungslink ist <strong><?php echo($this->expire); ?></strong>
            gültig. Solltest Du nicht innerhalb dieser Zeit auf den Link geklickt
            haben so wird Deine Anfrage automatisch gelöscht und Du kannst kein
            neues Passwort setzen!
        </div>
        <div class="modal-footer" style="border: 0; margin-top: 12px;">
            <button type="button" class="btn btn-success btn-sm submit-form">
                okay
            </button>
        </div>
    </div>
</div>

<div class="py-md-4 mx-auto" style="width: 35rem; padding-top: 3.5rem !important;">
    <div class="card card-block" style="padding: .75rem 1.25rem; border: .0625rem solid #c6c8ca; background-color: #d6d8d9">
        <h3 style="margin-bottom: 1.5rem;">Passwort rücksetzen</h3>
        <p>
            Du hast Dein Passwort verbaselt? Hier hast Du die Möglichkeit, es wieder
            rückzusetzen.
        </p>
        <div class="row">
            <label for="usr" class="col-sm-4 col-form-label">Benutzername</label>
            <div class="col-sm-7">
                <input
                    class="form-control form-control-sm"
                    type="text"
                    name="usr"
                    size="30"
                    maxlength="30"
                    value=""
                    title="Gib hier bitte Deinen Loginnamen ein"
                />
            </div>
        </div>
        <div class="row">
            <label for="pwd" class="col-sm-4 col-form-label">E-Mail</label>
            <div class="col-sm-7">
                <input
                    class="form-control form-control-sm "
                    type="text"
                    name="addr"
                    size="30"
                    maxlength="30"
                    value=""
                    title="Gib hier bitte Deine E-Mail-Adresse ein"
                />
                <div class="invalid-feedback">
                    Der Vorgang schlug fehl!
                </div>
            </div>
        </div>
        <div class="modal-footer" style="border: 0; margin-top: 12px;">
            <button type="button" class="btn btn-success btn-sm submit-form">
                anfordern
            </button>
            <button id="btnCancel" type="button" class="btn btn-danger btn-sm">
                abbrechen
            </button>
        </div>
    </div>
</div>
<input type="hidden" id="lastPage" value="<?php echo($this->lastPage); ?>" />
<script>
    $('#btnCancel').click(function() {
        let url = $('#lastPage').val().split('?');
        window.location.href = url[0];
    });
</script>