<div class="py-md-4 px-md-5">
    <header>
        <p>
            Bestätigungsnachricht wurde erfolgreich an
            <strong><?php echo($this->name); ?></strong>
            verschickt.
        </p>
        <p>
            Bitte klicke auf den Bestätigungslink den Du per E-Mail erhälst
            um Dein neues Passwort eingeben zu können.
        </p>
        <div class="alert alert-warning" role="alert">
            Der Bestätigungslink ist <strong><?php echo($this->expire); ?></strong>
            gültig. Solltest Du nicht innerhalb dieser Zeit auf den Link geklickt
            haben so wird Deine Anfrage automatisch gelöscht und Du kannst kein
            neues Passwort setzen!
        </div>
    </header>
</div>