    <div class="alert alert-info" role="alert">
        <strong>Hinweis: </strong>
        Gib hier bitte Dein neues Passwort ein und wiederhole es.
    </div>
    <div class="card card-block" style="padding: .75rem 1.25rem; border: .0625rem solid #c6c8ca; background-color: #d6d8d9">
        <form method="POST" action="?do="></form>
        <div class="form-group row">
            <label
                for="usr"
                class="form-control-label col-sm-2"
            >
                Passwort
            </label>
            <div class="col-sm-4">
                <input
                    id="usr"
                    class="<?php if($this->showError): ?> is-invalid <?php endif; ?> form-control form-control-sm"
                    type="password"
                    name="usr"
                    size="30"
                    maxlength="30"
                    value=""
                    title="Gib hier bitte Dein neues Passwort ein"
                />
            </div>

        </div>
        <div class="form-group row">
            <label
                for="addr"
                class="form-control-label col-sm-2"
            >
                Passwort wiederholen
            </label>
            <div class="col-sm-4">
                <input
                    id="addr"
                    class="<?php if($this->showError): ?> is-invalid <?php endif; ?> form-control form-control-sm"
                    type="password"
                    name="addr"
                    size="30"
                    maxlength="30"
                    value=""
                    title="Wiederhole hier bitte Dein Passwort"
                />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-offset-2 col-sm-10">
                <button
                    class="btn btn-success btn-sm"
                    id="btnUploadbulletinBoardArticle_"
                >
                    setzen
                </button>
                <button
                    class="btn btn-danger btn-sm"
                    id="btnCancelbulletinBoardArticle_"
                >
                    abbrechen
                </button>
            </div>
        </div>
    </div>

