<?php
/**
 *  SFW - SimpleFrameWork
 *
 *  Copyright (C) 2015  Stefan Paproth
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program. If not, see <http://www.gnu.org/licenses/agpl.txt>.
 *
 */
?>

<div class="modal fade" id="loginDialogModalCenter" tabindex="-1" role="dialog" aria-labelledby="acceptDialogModalCenter" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered " style="max-width: 560px;" role="document">
        <div class="modal-content" style="padding: .75rem 1.25rem; border: .0625rem solid #c6c8ca; background-color: #d6d8d9">
            <h3 style="margin-bottom: 1.5rem;">Anmelden</h3>
            <div class="card card-block" style="padding: .75rem 1.25rem; border: .0625rem solid #c6c8ca; background-color: #d6d8d9">
                <div style="padding-bottom: 1rem;">
                    Hallo <strong>Stefan</strong><?php #echo($this->firstname); ?>,<br />
                    Du wurdest erfolgreich angemeldet. Zum Abmelden klicke bitte oben rechts auf "<strong>abmelden</strong>".
                </div>
            </div>
            <div class="modal-footer" style="border: 0; margin-top: 12px;">
                <button type="button" class="btn btn-success btn-sm submit-form">okay</button>
            </div>
        </div>
    </div>
</div>
<div class="py-md-4 mx-auto" style="width: 35rem; padding-top: 3.5rem !important;">
    <?php if($this->isAllreadyLoggedIn): ?>
    <div class="alert alert-warning" role="alert">
        <strong>Hinweis: </strong> Du bist bereits als <strong><?php echo($this->firstname); ?></strong>
        angemeldet. Wenn Du Dich abmelden möchtest klicke bitte oben rechts auf <strong>abmelden</strong>.
    </div>
    <?php endif; ?>
    <div class="card card-block" style="padding: .75rem 1.25rem; border: .0625rem solid #c6c8ca; background-color: #d6d8d9">
        <h3 style="margin-bottom: 1.5rem;">Melde dich in deinem Konto an...</h3>
        <div class="row">
            <label for="usr" class="col-sm-4 col-form-label">Benutzername</label>
            <div class="col-sm-7">
                <input
                    id="usr"
                    class="form-control form-control-sm"
                    type="text"
                    name="usr"
                    size="30"
                    maxlength="30"
                    value=""
                />
            </div>
        </div>
        <div class="row">
            <label for="pwd" class="col-sm-4 col-form-label">Passwort</label>
            <div class="col-sm-7">
                <input
                    id="pwd"
                    class="form-control form-control-sm"
                    type="password"
                    name="pwd"
                    size="30"
                    maxlength="30"
                    value=""
                />
                <div class="hide invalid-feedback">
                    Die Anmeldung schlug fehl!
                </div>
            </div>
        </div>
        <div class="modal-footer" style="border: 0; margin-top: 12px;">
            <button id="btnLogin" type="button" class="btn btn-success btn-sm submit-form">
                okay
            </button>
            <button id="btnCancel" type="button" class="btn btn-danger btn-sm">
                abbrechen
            </button>
        </div>
        <?php if($this->loginResetPath != ''): ?>
        <div class="row">
            <div class="col-sm-7">
                <a class="loginLnk" href="<?php echo($this->loginResetPath); ?>">Passwort vergessen?</a>
            </div>
        </div>
        <?php endif; ?>
    </div>
</div>
<script>
    $("#usr").focus();
    $('#pwd').keyup(function(e) {
        if(e.keyCode === 13) {
            $('#btnLogin').trigger('click');
        }
    });

    $('#btnLogin').click(doLogin);
    $('#btnCancel').click(function() {
        var url = window.location.href.split('?');
        if(url.length != 1){
            window.location.href = url[0];
            return true;
        }
        window.location.reload();
    });

    function doLogin() {
        $('#btnLogin').prop('disabled', true);
        $('#btnCancel').prop('disabled', true);

        $.post('?do=authenticate', {usr: 'blab', pwd: 'bamm'}, success, "json");
    }

    function success(data, textStatus) {
        console.log(data);
        console.log(textStatus);
    }





(function(window, document, $, undefined) {

    function loginReady(data) {
        $('#ajaxloader').hide();

        var msg;
        if(data.error === undefined || data.error) {
            msg =
                '<strong>Achtung!</strong>' +
                '<p>' +
                'Die Anmeldung schlug fehl! Bitte prüfe Deine Zugangsdaten.' +
                '</p>';
            sfw_dialogbox.showOKDialogBox('Login', msg, function() {});
            $('#btnLogin').removeAttr('disabled');
            $('#btnCancel').removeAttr('disabled');
            $('#token').val(data.token);
            return;
        }
        msg =
            'Hallo ' + data.firstname + ',' +
            '<p>' +
            'Du wurdest erfolgreich angemeldet. ' +
            'Zum Abmelden klicke bitte oben rechts auf ' +
            '<strong>Logout</strong>.' +
            '</p>';
        sfw_dialogbox.showOKDialogBox('Login', msg, function() {
            var url = window.location.href.split('?');
            if(url.length == 1) {
                window.location.reload();
            } else {
                window.location.href = url[0];
            }
        });
        return;
    }

    function doLogoff() {
        var msg =
            'Du wurdest erfolgreich abgemeldet.' +
            'Um Dich erneut anzumelden klicke bitte oben ' +
            'rechts auf <strong>Login</strong>.';

        $.get(
            '/',
            {auth : 'logoff'},
            function() {
                sfw_dialogbox.showOKDialogBox(
                    'Logout',
                    msg,
                    function() {
                        window.location.reload();
                    }
                );
                return;
            }
        );
    }

    window.sfw_login = {
        isLoggedIn: function() {
            var msg =
                'Du wurdest nach längerer Inaktivität automatich abgemeldet.' +
                'Um Dich erneut anzumelden klicke bitte oben rechts auf ' +
                '<strong>Login</strong>.';

            $.getJSON(
                '/',
                {auth : 'check'},
                function(data){
                    if(data.islin) {
                        return;
                    }
                    window.sfw_dialogbox.showOKDialogBox(
                        'Automatisch abgemeldet',
                        msg,
                        function() {
                            window.location.reload();
                        }
                    );
                }
            );
        }
    };
})(window, document, jQuery);

</script>

