<?php
/**
 *  SFW - SimpleFrameWork
 *
 *  Copyright (C) 2015  Stefan Paproth
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program. If not, see <http://www.gnu.org/licenses/agpl.txt>.
 *
 */
?>
<div class="modal fade" id="loginDialogModalCenter" tabindex="-1" role="dialog" aria-labelledby="acceptDialogModalCenter" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Anmelden</h5>
            </div>
            <div class="modal-body">
                Hallo <strong id="firstName"></strong>,<br />
                Du wurdest erfolgreich angemeldet. Zum Abmelden klicke bitte oben rechts auf "<strong>abmelden</strong>".
            </div>
            <div class="modal-footer" margin-top: 12px;">
                <button id="btnLoginSuccess" type="button" class="btn btn-success btn-sm submit-form">okay</button>
            </div>
        </div>
    </div>
</div>
<div class="py-md-4 mx-auto" style="width: 35rem; padding-top: 3.5rem !important;">
    <?php if($this->isAllreadyLoggedIn): ?>
    <div class="alert alert-warning" role="alert">
        <strong>Hinweis: </strong> Du bist bereits als <strong><?php echo($this->firstname); ?></strong>
        angemeldet. Wenn Du Dich abmelden möchtest klicke bitte oben rechts auf <strong>abmelden</strong>.
    </div>
    <?php else:?>
    <div class="card card-block" style="padding: .75rem 1.25rem; border: .0625rem solid #c6c8ca; background-color: #d6d8d9">
        <h3 style="margin-bottom: 1.5rem;">Melde dich in deinem Konto an...</h3>
        <div class="row">
            <label for="usr" class="col-sm-4 col-form-label">Benutzername</label>
            <div class="col-sm-7">
                <input
                    id="usr"
                    class="form-control form-control-sm"
                    type="text"
                    name="usr"
                    size="30"
                    maxlength="30"
                    value=""
                />
            </div>
        </div>
        <div class="row">
            <label for="pwd" class="col-sm-4 col-form-label">Passwort</label>
            <div class="col-sm-7">
                <input
                    id="pwd"
                    class="form-control form-control-sm"
                    type="password"
                    name="pwd"
                    size="30"
                    maxlength="30"
                    value=""
                />
                <div class="invalid-feedback">Die Anmeldung schlug fehl!</div>
            </div>
        </div>
        <div class="modal-footer" style="border: 0; margin-top: 12px;">
            <button id="btnLogin" type="button" class="btn btn-success btn-sm submit-form">
                okay
            </button>
            <button id="btnCancel" type="button" class="btn btn-danger btn-sm">
                abbrechen
            </button>
        </div>
        <?php if($this->loginResetPath != ''): ?>
        <div class="row">
            <div class="col-sm-7">
                <a class="loginLnk" href="<?php echo($this->loginResetPath); ?>">Passwort vergessen?</a>
            </div>
        </div>
        <?php endif; ?>
    </div>
    <?php endif; ?>
</div>
<input type="hidden" id="lastPage" value="<?php echo($this->lastPage); ?>" />
<script>
    $("#usr").focus();
    $('#usr').keyup(function(e) {
        $('#usr').removeClass('is-invalid');
    });

    $('#pwd').keyup(function(e) {
        $('#pwd').removeClass('is-invalid');
        if(e.keyCode === 13) {
            $('#btnLogin').trigger('click');
        }
    });

    $('#btnLogin').click(doLogin);
    $('#btnCancel').click(returnToOrigin);

    function doLogin() {
        $('#btnLogin').prop('disabled', true);
        $('#btnCancel').prop('disabled', true);

        $.post(
            '?do=authenticate',
            {
                usr: $('#usr').val(),
                pwd: $('#pwd').val(),
                xss: $('#xssToken').val()
            },
            success,
            "json"
        );
    }

    function success(data, textStatus) {
        $('#xssToken').val(data.xss);
        if(data.error) {
            $('#btnLogin').prop('disabled', false);
            $('#btnCancel').prop('disabled', false);
            $('#usr').addClass('is-invalid');
            $('#pwd').addClass('is-invalid');
            return;
        }

        $('#firstName').html(data.data.user);
        $('#loginDialogModalCenter').modal({show: true})
        $('#btnLoginSuccess').click(returnToOrigin);
    }

    function returnToOrigin() {
        let url = $('#lastPage').val().split('?');
        window.location.href = url[0];
    }
</script>

