<div class="py-md-4 mx-auto" style="width: 35rem; padding-top: 3.5rem !important;">
    <div class="card card-block" style="padding: .75rem 1.25rem; border: .0625rem solid #c6c8ca; background-color: #d6d8d9">
        <h3 style="margin-bottom: 1.5rem;">Abgemeldet...</h3>
        Du wurdest erfolgreich abgemeldet.
        Um Dich erneut anzumelden klicke bitte oben rechts auf Login.
        <div class="modal-footer" style="border: 0; margin-top: 12px;">
            <button id="btnOkay" type="button" class="btn btn-success btn-sm submit-form">
                okay
            </button>
        </div>
    </div>
</div>
<input type="hidden" id="lastPage" value="<?php echo($this->lastPage); ?>" />
<script>
    $('#btnOkay').click(function() {
        let url = $('#lastPage').val().split('?');
        window.location.href = url[0];
    });
</script>