<h1>
    <?php echo($this->title); ?>
</h1>
<input id="path" type="hidden" name="path" value="/verein/allgemein/aktuelles" />
<?php if($this->permission->createAllowed()): ?>
<form style="padding: .75rem 1.25rem; border: .0625rem solid #c6c8ca; background-color: #d6d8d9; border-radius: .25rem;">
    <!--<div id="fileuploadArea_"></div>-->
    <div class="row">
        <label for="title" class="col-sm-2 col-form-label">Überschrift</label>
        <div class="col-sm-4">
            <input
                type="text"
                class="form-control form-control-sm"
                placeholder="Gib hier bitte die Überschrift ein..."
                name="title"
                value=""
                title="Gib hier bitte eine Überschrift ein."
                maxlength="100"
            />
            <div class="valid-feedback"></div>
        </div>
    </div>
    <div class="row">
        <label for="division" class="col-sm-2 col-form-label">Ressort</label>
        <div class="col-sm-4">
            <select
                class="custom-select form-control form-control-sm"
                name="division"
            >
                <?php foreach($this->divisions as $division): ?>
                <option value="<?php echo($division['Id']);?>"><?php echo($division['Name']);?></option>
                <?php endforeach; ?>
            </select>
            <div class="valid-feedback"></div>
        </div>
    </div>
    <div class="row">
        <label for="content" class="col-sm-2 col-form-label">Inhalt</label>
        <div class="col-sm-8">
            <textarea
                style="height: 10rem;"
                class="form-control form-control-sm"
                placeholder="Gib hier bitte den Inhalt ein..."
                name="content"
                title="Gib hier bitte den Inhalt ein."
            ></textarea>
        </div>
        <div class="valid-feedback"></div>
    </div>
    <div class="modal-footer" style="border: 0; margin-top: 12px;">
        <button type="button" class="btn btn-success btn-sm submit-form">
            speichern
        </button>
        <button type="reset" class="btn btn-danger btn-sm">
            abbrechen
        </button>
    </div>
</form>
<?php endif; ?>
<?php if(empty($this->items)): ?>
<?php echo($this->showNoData()); ?>
<?php else: ?>
<ul class="list-unstyled">
    <?php foreach($this->items as $item): ?>
    <li class="media my-4" id="<?php echo($item['id']);?>">
        <img style="width: 75px;" class="rounded mr-3" src="<?php echo($item['image']);?>" alt="Autor">
        <div class="media-body" style="border-left: 1px solid #929292; padding-left: 12px;">
            <h4 id="title_<?php echo($item['id']);?>" style="font-weight: bolder;" class="mt-0 mb-1"><?php echo($item['title']);?></h4>
            <small style="font-style: italic;">
                <div>Ressort <?php echo($item['resname']); ?></div>
                <div>Erstellt von <?php echo($item['mailaddr']);?> am <?php echo((string)$item['date']); ?></div>
            </small>
            <div style="margin-top: 0.25rem;"><?php echo($item['content']);?></div>
        </div>
        <?php if($this->permission->deleteAllAllowed() || ($this->permission->deleteOwnAllowed() && $item['ownEntry'])): ?>
        <button
            type="button"
            class="btn btn-danger btn-sm"
            data-toggle="modal"
            data-target="#acceptDialogModalCenter"
            data-item-id="<?php echo($item['id']);?>"
        >
            löschen
        </button>
        <?php endif; ?>
    </li>
    <?php endforeach; ?>
</ul>
<?php endif;