<div style="position: relative;">
    <img
        style="max-width:100%;"
        alt=""
        src="/public/layout/<?php echo(rand(1,3)); ?>t.jpg"
    />
    <div style="float: left; position: absolute; z-index: 1000; right: 15px; top: 15px;">
        <a class="externlinksimple" href="http://www.von-Schilling-Bogensport.de" title="von Schilling Bogensport">
            <img style="height: 130px; padding-right: 15px;" class="rounded" src="/public/layout/HD_D80_20120526_1.png" alt="von Schilling Bogensport">
        </a>
        <a class="externlinksimple" href="http://www.stadtwerke-springe.de/" title="Stadtwerke Springe">
            <img style="height: 130px;" class="rounded" src="/public/layout/swspringe.png" alt="Stadtwerke Springe">
        </a>
    </div>
</div>
