<div class="container" style="margin-top:35px;" >
    <div class="jumbotron" style="color: #8c8c8c; background-color: #d6d8d9; border-color: #c6c8ca" >
        <h1 class="display-3"><?php echo($this->title); ?></h1>
        <p class="lead"><?php echo($this->caption); ?></p>
        <p><?php echo(nl2br($this->description)); ?></p>
        <?php if(isset($this->debugData)): ?>
        <hr class="my-4">
        <p>
            <pre>
                <?php echo(PHP_EOL . htmlentities(print_r($this->debugData, true))); ?>
            </pre>
        </p>
        <?php endif; ?>
    </div>
</div>
