<?php

/**
 *  SFW2 - SimpleFrameWork
 *
 *  Copyright (C) 2017  Stefan Paproth
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program. If not, see <http://www.gnu.org/licenses/agpl.txt>.
 *
 */

?>
<div id="<?php echo($this->id);?>">
    <p class="card-text">
        <a
            href="<?php echo($this->image); ?>"
            rel="lightbox-gallerie"
        >
            <img
                class="img-fluid rounded"
                title="<?php echo($this->title);?>"
                alt="<?php echo($this->title);?>"
                src="<?php echo($this->image); ?>"
            />
        </a>
        <?php if($this->permission->deleteAllAllowed() || ($this->permission->deleteOwnAllowed() && $this->ownEntry)): ?>
        <button
            type="button"
            class="btn btn-danger btn-sm"
            data-toggle="modal"
            data-target="#acceptDialogModalCenter"
            data-item-id="<?php echo($this->id);?>"
        >
            löschen
        </button>
        <?php endif;?>
    </p>
    <input type="hidden" id="title_<?php echo($this->id);?>" value="<?php echo($this->title); ?>" />
    <small class="blogheader">
        Erstellt von <?php echo($this->mailaddr); ?> am <?php echo($this->date); ?>;
        Quelle: <?php echo($this->source); ?>&nbsp;&nbsp;
    </small>
</div>
