<?php

/**
 *  SFW2 - SimpleFrameWork
 *
 *  Copyright (C) 2017  Stefan Paproth
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program. If not, see <http://www.gnu.org/licenses/agpl.txt>.
 *
 */

?>
<h1>Pressemitteilungen</h1>
<p>
    Hier ein paar interessante Zeitungsartikel über <?php echo($this->about); ?>
</p>
<?php if(!$this->permission->createAllowed()): ?>
<div class="alert alert-dark" role="alert">
    <strong>Hinweis</strong><br />
    Solltest Du ebenfalls einen interessanten Artikel entdeckt haben
    dann immer her damit. Auch alte Mitteilungen sind gerne willkommen.
    Am Besten Du schickst ihn per E-Mail an <?php echo($this->mailaddr);?>.
    Bitte gib den Name der Zeitung und das jeweilige Datum mit an.
</div>
<?php else:?>
<input id="path" type="hidden" name="path" value="/verein/allgemein/aktuelles" />
<form style="padding: .75rem 1.25rem; border: .0625rem solid #c6c8ca; background-color: #d6d8d9; border-radius: .25rem;">
    <!--<div id="fileuploadArea_"></div>-->
    <div class="row">
        <label for="title" class="col-sm-4 col-form-label">Artikel</label>
        <div class="col-sm-7">
            <input
                type="text"
                class="form-control form-control-sm"
                placeholder="Gib hier bitte die Überschrift ein..."
                maxlength="100"
                title="Gib hier bitte die Überschrift ein..."
                id="title"
                name="title"
                value=""
                required
            />
        </div>
    </div>
    <div class="row">
        <label for="date" class="col-sm-4 col-form-label">Erschienen am</label>
        <div class="col-sm-4">
            <input
                id="date"
                class="form-control form-control-sm"
                type="date"
                name="date"
                value=""
                title="Gib hier bitte das Erscheinungsdatum an..."
                maxlength="10"
                required
            />
        </div>
    </div>
    <div class="row">
        <label for="newspaper" class="col-sm-4 col-form-label">In folgender Zeitung</label>
        <div class="col-sm-4">
            <input
                id="newspaper"
                type="text"
                class="form-control form-control-sm"
                name="newspaper"
                value=""
                list="newspapers"
                placeholder="Gib hier bitte die Zeitung an..."
                title="Gib hier bitte die Quelle (Zeitung) ein."
                maxlength="5"
                required
            >
            <datalist id="newspapers">
                <option value="NDZ" />
                <option value="HAZ" />
                <option value="NP" />
            </datalist>
        </div>
    </div>
    <div class="modal-footer" style="border: 0; margin-top: 12px;">
        <button type="button" class="btn btn-success btn-sm submit-form">
            speichern
        </button>
        <button type="reset" class="btn btn-danger btn-sm">
            abbrechen
        </button>
    </div>
</form>
<?php endif; ?>
<div style="min-height: 44px;"></div>
<?php foreach($this->items as $item): ?>
<?php echo($item); ?>
<?php endforeach;