<?php
/**
 *  SFW - SimpleFrameWork
 *
 *  Copyright (C) 2015  Stefan Paproth
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program. If not, see <http://www.gnu.org/licenses/agpl.txt>.
 *
 */
?>
<header>
    <h1
        id="title"
        <?php if($this->permission->createAllowed()): ?>
        class="editable"
        style="text-decoration: none;"
        <?php endif;?>
        contenteditable="true"
    >
        <?php echo($this->content['title']);?>
    </h1>
</header>
<?php if($this->permission->createAllowed()): ?>
<input
    id="hiddentitle"
    type="hidden"
    value="<?php echo($this->content['title']);?>"
/>
<div id="previewarea">
    <div class="nodata <?php if($this->content['content'] != ''): ?>noshow <?php endif;?>">
        <br />
        <strong class="indent">
            <i>Zur Zeit liegen keine Daten vor!</i>
        </strong>
    </div>
    <div id="htmlcontentinner">
        <div id="htmlcontentdata">
            <?php echo($this->content['content']);?>
        </div>
    </div>
    <i>
        <?php if($this->content['name'] != '' ):?>
        Erstellt von
        <?php endif; ?>
        <?php echo($this->content['name']); ?>
        <?php if($this->content['name'] != '' && $this->content['date'] != ''): ?> am <?php endif; ?>
        <time pubdate="pubdate"><?php echo($this->content['date']); ?></time>
    </i>
    <div style="margin-top: 20px;">
        <div style="float: right;">
            <button
                class="btn btn-success btn-sm"
                id="btnEdit"
                type="submit"
            >
                bearbeiten
            </button>
        </div>
    </div>
</div>
<div id="editarea" class="noshow">
    <textarea
        id="content"
        cols="250"
        rows="30"
        style="width: 700px;"
    ><?php echo($this->content['content']);?>
    </textarea>
    <br />
    <div style="margin-top: 20px;">
        <div style="float: right;">
            <button
                class="btn btn-danger btn-sm"
                id="btnBack"
                type="submit"
            >
                abbrechen
            </button>
            <button
                class="btn btn-success btn-sm"
                id="btnSave"
                type="submit"
                value="speichern"
            >
                speichern
            </button>
        </div>
    </div>
</div>
<?php else: ?>
<?php if($this->content['content'] == ''): ?>
<div class="alert alert-dark" role="alert">
    <strong>Anmerkung:</strong> Zur Zeit liegen keinen aktuellen Anmerkungen vor
</div>
<?php else: ?>
<?php echo($this->content['content']);?>
<?php endif; ?>
<?php if($this->content['date'] != ''): ?>
<div class="modificationDate">
    Stand:
    <time pubdate="pubdate" >
        <?php echo($this->content['date']); ?></time><?php echo($this->content['shortna']); ?>
</div>
<?php endif; ?>
<?php endif;
