<h1>Download</h1>
<p>
    Auf dieser Seite findest Du Dokumente zum herunterladen.
</p>
<input id="path" type="hidden" name="path" value="/verein/allgemein/download" />
<?php if(!$this->permission->createAllowed()): ?>
<div class="alert alert-dark" role="alert">
    Ich bemühe mich, die Seite stets aktuell zu halten. Solltest
    Du dennoch feststellen, dass ein Dokument veraltet ist oder
    Fehler enthält, dann gib mir bitte <?php echo($this->mailaddr);?>
</div>
<?php else: ?>
<form style="padding: .75rem 1.25rem; border: .0625rem solid #c6c8ca; background-color: #d6d8d9; border-radius: .25rem;">
    <!--<div id="fileuploadArea_"></div>-->
    <div class="row">
        <label for="title" class="col-sm-3 col-form-label">Beschreibung</label>
        <div class="col-sm-8">
            <input
                type="text"
                class="form-control form-control-sm"
                placeholder="Hier kommt die Beschreibung hin..."
                maxlength="100"
                title="Gib hier bitte eine kurze Beschreibung der Datei ein."
                id="title"
                name="title"
                value=""
                required
            />
        </div>
    </div>
    <div class="row">
        <label for="division" class="col-sm-3 col-form-label">Ressort</label>
        <div class="col-sm-4">
            <select
                class="custom-select form-control form-control-sm"
                id="division"
                name="division"
            >
                <?php foreach($this->divisions as $division): ?>
                <option value="<?php echo($division['Id']);?>"><?php echo($division['Name']);?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="modal-footer" style="border: 0; margin-top: 12px;">
        <button type="button" class="btn btn-success btn-sm submit-form">
            speichern
        </button>
        <button type="reset" class="btn btn-danger btn-sm">
            abbrechen
        </button>
    </div>
</form>
<div id="fileuploadArea_<?php echo($this->getTemplateId()); ?>" ></div>
<?php endif; ?>
<?php if(!count($this->entries) && !$this->editable):?>
<div class="alert alert-dark" role="alert">
    <strong>Anmerkung:</strong> Es gibt keine Daten
</div>
<?php endif; ?>
<?php if(count($this->entries) || $this->editable):?>
<?php foreach($this->entries as $k => $v): ?>
<div style="min-height: 44px;"></div>
<table class="nowrap table-sm table table-striped" style="border-top:0; border-bottom: 0;">
    <thead class="thead-dark">
        <tr>
            <th style="color: #e8e8e8;;background-color: #898989; border-top:0; border-bottom: 0;" scope="col" colspan="3"><?php echo($k); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($v as $item): ?>
        <tr id="<?php echo($item['id']);?>">
            <td style="width: 30px; border-top:0; border-bottom: 0;">
                <img alt="" src="<?php echo($item['icon']);?>" />
            </td>
            <td style="border-top:0; border-bottom: 0;">
                <a href="/" id="title_<?php echo($item['id']);?>">
                    <?php echo($item['description']);?>
                </a>
            </td>
            <td style="width: 100px; border-top:0; border-bottom: 0;">
                <?php if($this->permission->deleteAllAllowed() || ($this->permission->deleteOwnAllowed() && $item['ownEntry'])): ?>
                <button
                    type="button"
                    class="btn btn-danger btn-sm"
                    data-toggle="modal"
                    data-target="#acceptDialogModalCenter"
                    data-item-id="<?php echo($item['id']);?>"
                >
                    löschen
                </button>
                <?php endif; ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php endforeach; ?>
<?php endif; ?>
<div class="modificationDate">
    Stand: <time pubdate="pubdate"><?php echo($this->modificationDate); ?></time>
</div>
