<h1>Ansprechpartner</h1>
<p>
    Ansprechpartner bei Fragen, für Vorschläge etc.
</p>
<div class="alert alert-dark" role="alert">
    <strong>Anmerkung</strong>
    <p style="margin-bottom: 0">
    Die aktuelle Fassung steht auch als
    <a
        class="link"
        href="/verein/webseite/download"
    >Download</a>
    zur Verfügung. Stand: 13. Januar 2011
    </p>
</div>


<?php foreach($this->entries as $k => $v): ?>
<div style="min-height: 44px;"></div>
<table class="nowrap table-sm table table-striped" style="border-top:0; border-bottom: 0;">
    <thead class="thead-dark">
        <tr>
            <th style="color: #e8e8e8;;background-color: #898989; border-top:0; border-bottom: 0;" scope="col" colspan="4"><?php echo($k); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($v as $item): ?>
        <tr>
            <th style="border-top:0; border-bottom: 0; white-space: nowrap;">
                <?php echo($item['position']); ?>
            </th>
            <td style="border-top:0; border-bottom: 0; white-space: nowrap;">
                <?php echo($item['name']);?>
            </td>
            <td style="border-top:0; border-bottom: 0; white-space: nowrap;">
                <?php echo($item['phone']);?>
            </td>
            <td style="border-top:0; border-bottom: 0; white-space: nowrap;">
                <?php echo($item['emailaddr']);?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php endforeach; ?>
<div class="modificationDate">
Stand: <?php echo($this->modificationDate); ?>
</div>