<h1>Unsere Sponsoren</h1>
<p>
    Ohne die Hilfe und Unterstützung unserer Sponsoren wäre die
    Arbeit des Sportvereins kaum noch möglich.
</p>
<p>
    Der VfV Concordia Alvesrode möchte sich daher an dieser Stelle bei allen Sponsoren
    bedanken und ein herzliches Dankeschön sagen.
</p>
<?php foreach($this->items as $chunks): ?>
<div class="row">
    <?php foreach($chunks as $item): ?>
    <div style="padding: 0.9375rem;" class="col-md-3">
        <a
            class="externlinksimple"
            href="<?php echo($item['URL']); ?>"
            title="<?php echo($item['Title']); ?>"
        >
            <img
                class="rounded img-fluid"
                src="<?php echo($item['Source']); ?>"
                alt="<?php echo($item['Title']); ?>"
            />
        </a>
    </div>
    <?php endforeach; ?>
</div>
<?php endforeach; ?>
<div class="modificationDate">
    Stand: <time pubdate="pubdate"><?php echo($this->modificationDate); ?></time>
</div>
