<h1><?php echo($this->caption);?></h1>
<p>
    Um Dir die Bilder der jeweiligen Galerie anzuschauen, klicke bitte auf das
    jeweilige Vorschaubild.
</p>
<div class="alert alert-dark" role="alert">
    <strong>Anmerkung</strong>
    <p style="margin-bottom: 0">
    Wenn ein Bild gelöscht werden soll dann schreib bitte einen entsprechenden Hinweis an
    <?php echo($this->webmaster); ?>
    </p>
</div>
<p>
    Du hast ebenfalls Bilder? Immer her damit. Wenn Du magst, kannst Du
    Dir die jeweiligen Galerien auch als Zip-Datei herunterladen. Die Archive
    enthalten die Bilder in der besten Auflösung...
</p>
<?php if($this->permission->createAllowed()): ?>
<form style="padding: .75rem 1.25rem; border: .0625rem solid #c6c8ca; background-color: #d6d8d9; border-radius: .25rem;">
    <div class="row">
        <label for="caption" class="col-sm-2 col-form-label">Name</label>
        <div class="col-sm-4">
            <input
                class="form-control form-control-sm"
                type="text"
                name="caption"
                value=""
                placeholder="Gib hier den Namen der Gallerie ein..."
                maxlength="50"
                title="Gib hier bitte die Überschrift der neuen Galerie ein."
            />
        </div>
    </div>
    <div class="row">
        <label for="description" class="col-sm-2 col-form-label">
            Beschreibung
        </label>
        <div class="col-sm-9">
            <textarea
                class="form-control form-control-sm"
                name="description"
                placeholder="Hier kommt die Beschreibung rein ..."
                title="Hier kommt der Inhalt hin. Max. 65.535 Buchstaben"
                cols="30"
                rows="10"
                maxlength="65535"
            ></textarea>
        </div>
    </div>
    <div class="modal-footer" style="border: 0; margin-top: 12px;">
        <button type="button" class="btn btn-success btn-sm submit-form">
            speichern
        </button>
        <button type="reset" class="btn btn-danger btn-sm">
            abbrechen
        </button>
    </div>
</form>
<?php endif; ?>
<?php if(count($this->galleries)): ?>
<?php foreach($this->galleries as $k => $v1):?>
<div style="display: inline-block;margin-bottom: 35px; background-color: #fff; background-clip: border-box; border: 1px solid rgba(0,0,0,.125); border-radius: .25rem; width: 600px;">
    <a href="/">
        <img class="rounded-left float-left" src="<?php echo($v1['preview']); ?>" alt="<?php echo($v1['name']);?>" />
    </a>
    <div class="container" style="margin-left: 12rem; margin-top: 0.7rem;">
        <div class="row">
            <div class="col-sm-3"><h5><strong>Name</strong></h5></div>
            <div class="col-sm-3"><h5><?php echo($v1['name']);?></h5></div>
        </div>
        <div class="row">
            <div class="col-sm-3"><strong>Datum</strong></div>
            <div class="col-sm-3"><?php echo($v1['date']);?></div>
        </div>
        <div class="row">
            <div class="col-sm-3"><strong>Erstellt von</strong></div>
            <div class="col-sm-3"><?php echo($v1['creator']);?></div>
        </div>
        <div class="row">
            <div class="col-sm-3"><strong>Download</strong></div>
            <div class="col-sm-3"><a class="download" href="<?php echo($v1['dllink']);?>"><?php echo($v1['filename']); ?></a></div>
        </div>
    </div>
</div>









<?php /*
        <?php if($this->editable): ?>
        <button class="btn btn-danger btn-sm">
            löschen
        </button>
        <?php endif; ?>

     */?>
    <?php endforeach;?>

<?php else: ?>
<?php #echo($this->showNoData());?>
<?php endif; ?>
<div class="modificationDate">
    Stand: <time pubdate="pubdate"><?php echo($this->modificationDate); ?></time>
</div>
