<h1>Anmelden</h1>
<p>
    Du möchtest dem VfV Concordia beitreten?<br/>
    Super, am besten Du setzt Dich mit dem Ansprechpartner der jeweiligen Sparte
    in Verbindung.
</p>
<div class="alert alert-dark" role="alert">
    <strong>Anmerkung</strong>
    <p style="margin-bottom: 0">
    Die E-Mail-Adressen findest Du in der Rubrik
    <a class="link" href="/verein/kontakt">Kontakte</a>
    </p>
</div>
<p>
    Alternativ kannst Du natürlich auch einfach zum Training gehen. Dort
    erhältst Du dann vom Spartenleiter ein Anmeldeformular.
</p>
<p>
    Die Trainingszeiten kannst Du hier auf dieser Homepage in der jeweiligen
    Sparte einsehen.
</p>
<ul>
    <li>
        Trainingszeiten
        <a class="link" href="/fussball/start/termine" >Fussball</a>
    </li>
    <li>
        Trainingszeiten
        <a class="link" href="/tischtennis/start/termine">Tischtennis</a>
    </li>
    <li>
        Trainingszeiten
        <a class="link" href="/turnen/start/termine">Turnen</a>
    </li>
    <li>
        Trainingszeiten
        <a class="link" href="/bogenschiessen/start/termine">Bogenschießen</a>
    </li>
</ul>
<p>
    Informationen zum aktuellen Jahresbeitrag kannst Du
    <a class="link" href="/verein/info/beitrag">hier</a> bekommen.
</p>
<div class="modificationDate">
    Stand: <time pubdate="pubdate"><?php echo($this->modificationDate); ?></time>
</div>


