<h1>Vereinsbeitrag</h1>
<div class="alert alert-dark" role="alert">
    <strong class="alert-heading">Anmerkung</strong>
    <p style="margin-bottom: 0">
    Eintrittsformulare sind bei den jeweiligen Spartenleitern erhältlich.
    Stand: Juli 2015
    </p>
    <?php /* FIXME reparierenn
    Stand: <?php echo($this->modiDate->getMonthName()); ?>
    <?php echo($this->modiDate->getYear()); ?>
     */?>
</div>
<h3>Beitragsübersicht</h3>
<ol>
    <li>Einzeljahresbeitrag:
        <ol>
            <li>
                Erwachsene:<br />
                Aktiv: 60,00 € jährlich (entspricht mtl. 5,00 €)<br/>
                Passiv: 48,00 € jährlich (entspricht mtl. 4,00 €)
            </li>
            <li>Jugendliche bis zum 18. Lebensjahr:<br />
                36,00 € jährlich (entspricht mtl. 3,00 €)
            </li>
            <li>
                Schüler, Auszubildende, Studenten bei entsprechendem Nachweis:<br />
                36,00 € jährlich (entspricht mtl. 3,00 €)
            </li>
            <li>
                Wehrpflichtige bei entsprechendem Nachweis:<br />
                beitragsfrei
            </li>
        </ol>
    </li>
    <li>Familienbeitrag: *)<br />
        120,00 € jährlich (entspricht mtl. 10,00 €)
    </li>
    <li>
        Zusätzlicher Spartenbeitrag beim Bogenschießen: <br />
        <ol>
            <li>Erwachsene:<br />
                30,00 € jährlich (entspricht mtl. 2,50 €)
            </li>
            <li>Jugendliche bis zum 18. Lebensjahr:<br />
                20,00 € jährlich (entspricht mtl. 1,67 €)
            </li>
        </ol>
    </li>
</ol>
<p>
    *)
    <i>
       Der Familienbeitrag umfasst alle Mitglieder einer Familie
       (Eltern, Kinder u. Jugendliche bis zum 18. Lebensjahr sowie Schüler,
       Studenten u. Auszubildende bis zum Ende ihrer Ausbildung).
    </i>
</p>
<p>
    <i>
        Jugendliche, die das 18. Lebensjahr vollendet haben und sich nicht
        mehr in einer Ausbildung befinden, scheiden automatisch aus dem
        Familienbeitrag aus und haben den Einzelbeitrag zu entrichten.
    </i>
</p>
<br />
<h3>Fälligkeit des Beitrages</h3>
<p>
    Der Einzelbetrag wird einmalig am 30. Juni eines jeden Jahres fällig.
    Der Familienbeitrag wird jeweils zur Hälfte am 31. März und am 30. September
    eines jeden Jahres fällig.
</p>
<p>
    Der Spartenbeitrag wird entsprechend der
    Einstufung in Einzel- bzw. Familienmitgliedschaft erhoben.
    Sollte der Vereinsbeitritt nach dem 10. Juni erfolgen, so wird der Beitrag
    am 20. Dezember d. J. fällig.
</p>
<br />
<h3>Einzug der Beiträge</h3>
<p>
    Die Einzelbeiträge werden einmalig im Juli eines jeden Jahres fällig.
    Sollte der Vereinsbeitritt nach dem Juni erfolgen, so wird der Beitrag
    am Ende des Jahres fällig.
</p>
<p>
    Der Familienbeitrag wird grundsätzlich zu je 60,00 € im März und
    September fällig.
</p>
<p>
    Nach Absprache mit dem Kassenwart bzw. den jeweiligen Spartenleitern
    kann der Familienbeitrag auch einmalig in voller Höhe von 120,00 €
    eingezogen werden. Die Abbuchung erfolgt dann im Juni des Jahres.
</p>
<p>
    Sofern nicht gesondert vereinbart, werden die Beiträge zu den og.
    Terminen von Ihrem angegebenen  Konto per Lastschrift vom Verein
    eingezogen.
</p>
<p>
    Sollten Kontoänderungen Ihrerseits auftreten, so bitten wir um
    schnellstmögliche schriftliche Information, um Rückbuchungen und somit
    unnötige Kosten zu vermeiden.
</p>
<p>
    Durch nicht gemeldete Änderungen entstehende Kosten werden dem
    Beitragspflichtigen in Rechnung gestellt.
</p>
<br />
<h3>Austritt aus dem Verein</h3>
<p>
    Ein Austritt aus dem Verein ist jeweils zum 30.06. oder 31.12 eines
    Jahres möglich und die Kündigung muss spätestens einen Monat vorher
    eingereicht werden.
</p>
Der Austritt aus dem Verein ist schriftlich zu erklären und entweder
<ul>
    <li>dem zuständigen Spartenleiter zu übergeben</li>
    <li>bei einem der vier Vorstandsmitglieder persönlich abzugeben</li>
    <li>per Post an den Kassenwart zu übersenden<br />
        (zur Zeit: Volker Hinze, 31832 Springe, Angerstr. 21)
    </li>
</ul>
<div class="modificationDate">
    Stand: <time pubdate="pubdate"><?php echo($this->modificationDate); ?></time>
</div>

