<h1>Wissenswertes über die Sparte Bogenschießen</h1>
<p>
    Die Bogensparte des VfV Concordia Alvesrode besteht seit dem 01.10.2011.
</p>
<p>
    Im Winterhalbjahr - vom 01.10. bis zum 31.03. - wird in der
    Helmut-Schmieder-Halle trainiert. Im Sommerhalbjahr - vom 01.04. bis zum 30.09. -
    wird der Trainingsbetrieb auf der hinteren Seite des Sportgeländes ausgeübt.
</p>
<p>
    Die Abteilung besteht zur Zeit aus rund 50 Mitgliedern. Da die Sparte
    verhältnismäßig neu ist, sind alle Sportgeräte in einem tadellosen Zustand.
    Es sind für Anfänger eine ausreichende Anzahl an Übungsbögen vorhanden.
</p>
<img
    class="rounded float-left mr-2"
    alt=""
    src="/public/layout/bogen.jpg"
/>
<h4>Historie</h4>
<p>
    Das Bogenschießen ist ursprünglich eine der ältesten Jagdformen der Menschheit
    und spielte lange Zeit als Fernwaffe in kriegerischen Auseinandersetzungen eine
    bedeutsame Rolle.
</p>
<p>
    Heute ist das Schießen auf standardisierte Zielscheiben mit Recurvebögen,
    an denen Zielvorrichtungen und Stabilisatoren angebaut sind, die am weitesten
    verbreitete Bogensportart.
</p>
<p>
    Der verwendete Bogen, der häufig als "olympischer Bogen" bezeichnet wird, ist
    ein technologisch hoch entwickeltes Sportgerät, mit welchem genaue
    Treffer auf große Distanzen erzielt werden können.
</p>
<p>
    Das Bogenschießen zählt zu den Präzisionssportarten. Bogenschießen gehört seit
    1972 zu den Olympischen Sportarten. Zuvor war es bereits in den Jahren 1900,
    1904, 1908 und 1920 im Programm der Olympischen Spiele vertreten.
    <br />
    <span style="font-size: 0.65em;">(Quelle: Wikipedia)</span>
</p>
<div class="modificationDate">
    Stand: <time pubdate="pubdate"><?php echo($this->modificationDate); ?></time>
</div>