<h1>Datenschutz&shy;erklärung</h1>
<p>
    <i>Angaben gemäß § 13 TMG<br /><br /></i>
</p>
<p><strong>Geltungsbereich</strong></p>
<p>
    Diese Datenschutzerklärung klärt Nutzer über die Art, den Umfang und Zwecke
    der Erhebung und Verwendung personenbezogener Daten durch den
    verantwortlichen Anbieter
    <div class="indent">
        VfV Concordia Alvesrode von 1919 e. V.
        <br />
        Neuer Wiesenweg 1
        <br />
        <br />
        31832 Springe
        <br />
        <br />
        <strong>Vorsitzender:</strong>
        <br />
        <?php echo($this->chairman);?>
        <br />
        <br />
        <strong>Kontakt:</strong>
        <br />
        E-Mail: <?php echo($this->mailaddr); ?>
    </div>
    <br />
    auf dieser Website (im folgenden “Angebot”) auf.
    <br />
    <br />
    Die rechtlichen Grundlagen des Datenschutzes finden sich im
    Bundesdatenschutzgesetz (BDSG) und dem Telemediengesetz (TMG).
</p>
<br />
<p><strong>Zugriffsdaten/ Server-Logfiles</strong></p>
<p>
    Der Anbieter (beziehungsweise sein Webspace-Provider) erhebt Daten über
    jeden Zugriff auf das Angebot (so genannte Serverlogfiles). Zu den
    Zugriffsdaten gehören:
    <br />
    <br />
    Name der abgerufenen Webseite, Datei, Datum und Uhrzeit des Abrufs,
    übertragene Datenmenge, Meldung über erfolgreichen Abruf, Browsertyp nebst
    Version, das Betriebssystem des Nutzers, Referrer URL (die zuvor besuchte
    Seite), IP-Adresse und der anfragende Provider.
    <br />
    <br />
    Der Anbieter verwendet die Protokolldaten nur für statistische Auswertungen
    zum Zweck des Betriebs, der Sicherheit und der Optimierung des Angebotes.
    Der Anbieterbehält sich jedoch vor, die Protokolldaten nachträglich zu
    überprüfen, wenn aufgrund konkreter Anhaltspunkte der berechtigte Verdacht
    einer rechtswidrigen Nutzung besteht.
</p>
<br />
<p><strong>Umgang mit personenbezogenen Daten</strong></p>
<p>
    Personenbezogene Daten sind Informationen, mit deren Hilfe eine Person
    bestimmbar ist, also Angaben, die zurück zu einer Person verfolgt werden
    können. Dazu gehören der Name, die Emailadresse oder die Telefonnummer.
    Aber auch Daten über Vorlieben, Hobbies, Mitgliedschaften oder welche
    Webseiten von jemandem angesehen wurden zählen zu personenbezogenen
    Daten.
    <br />
    <br />
    Personenbezogene Daten werden von dem Anbieter nur dann erhoben, genutzt
    und weiter gegeben, wenn dies gesetzlich erlaubt ist oder die Nutzer in
    die Datenerhebung einwilligen.
</p>
<br />
<p><strong>Kontaktaufnahme</strong></p>
<p>
    Bei der Kontaktaufnahme mit dem Anbieter (zum Beispiel per Kontaktformular
    oder E-Mail) werden die Angaben des Nutzers zwecks Bearbeitung der Anfrage
    sowie für den Fall, dass Anschlussfragen entstehen, gespeichert.
</p>
<br />
<p><strong>Kommentare und Beiträge</strong></p>
<p>
    Wenn Nutzer Kommentare im Blog oder sonstige Beiträge hinterlassen, werden
    ihre IP-Adressen gespeichert. Das erfolgt zur Sicherheit des Anbieters,
    falls jemand in Kommentaren und Beiträgen widerrechtliche Inhalte schreibt
    (Beleidigungen, verbotene politische Propaganda, etc.). In diesem Fall kann
    der Anbieter selbst für den Kommentar oder Beitrag belangt werden und ist
    daher an der Identität des Verfassers interessiert.
</p>
<br />
<p><strong>Newsletter</strong></p>
<p>
    Mit dem Newsletter informieren wir Dich über uns und unsere Angebote.
    <br />
    <br />
    Wenn Du den Newsletter empfangen möchest, benötigen wir von Dir eine
    valide Email-Adresse sowie Informationen, die uns die Überprüfung
    gestatten, dass Du der Inhaber der angegebenen Email-Adresse bist bzw.
    deren Inhaber mit dem Empfang des Newsletters einverstanden ist. Weitere
    Daten werden nicht erhoben. Diese Daten werden nur für den Versand der
    Newsletter verwendet und werden nicht an Dritte weiter gegeben.
    <br />
    <br />
    Mit der Anmeldung zum Newsletter speichern wir Deine IP-Adresse und das Datum
    der Anmeldung. Diese Speicherung dient alleine dem Nachweis im Fall, dass
    ein Dritter eine Emailadresse missbraucht und sich ohne Wissen des
    Berechtigten für den Newsletterempfang anmeldet.
    <br />
    <br />
    Deine Einwilligung zur Speicherung der Daten, der Email-Adresse sowie deren
    Nutzung zum Versand des Newsletters kannst Du jederzeit widerrufen. Der
    Widerruf kann über einen Link in den Newslettern selbst oder per Mitteilung
    an die oben stehenden Kontaktmöglichkeiten erfolgen.
</p>
<br />
<p><strong>Cookies</strong></p>
<p>
    Cookies sind kleine Dateien, die es ermöglichen, auf dem Zugriffsgerät der
    Nutzer (PC, Smartphone o.ä.) spezifische, auf das Gerät bezogene
    Informationen zu speichern. Sie dienen zum einem der Benutzerfreundlichkeit
    von Webseiten und damit den Nutzern (z.B. Speicherung von Logindaten). Zum
    anderen dienen sie, um die statistische Daten der Webseitennutzung zu
    erfassen und sie zwecks Verbesserung des Angebotes analysieren zu können.
    Die Nutzer können auf den Einsatz der Cookies Einfluss nehmen. Die meisten
    Browser verfügen eine Option mit der das Speichern von Cookies eingeschränkt
    oder komplett verhindert wird. Allerdings wird darauf hingewiesen, dass die
    Nutzung und insbesondere der Nutzungskomfort ohne Cookies eingeschränkt
    werden.
</p>
<br />
<p><strong>Widerruf, Änderungen, Berichtigungen und Aktualisierungen</strong></p>
<p>
    Der Nutzer hat das Recht, auf Antrag unentgeltlich Auskunft zu erhalten über
    die personenbezogenen Daten, die über ihn gespeichert wurden. Zusätzlich hat
    der Nutzer das Recht auf Berichtigung unrichtiger Daten, Sperrung und
    Löschung seiner personenbezogenen Daten, soweit dem keine gesetzliche
    Aufbewahrungspflicht entgegensteht.
    <br />
</p>
<div class="modificationDate">
    Stand: <time pubdate="pubdate"><?php echo($this->modificationDate); ?></time>
</div>
