<h1>Wissenswertes über die Sparte Fussball</h1>
<p>
    Am 04. Juni 1919 wurde der „Verein für Volkssport (VfV) Concordia Alvesrode“
    als reiner Fußballverein gegründet. Obwohl im Laufe der Jahre wiederholt Versuche
    gestartet wurden, auch andere Sportarten zu betreiben, scheiterte dies zunächst
    an den fehlenden Übungsmöglichkeiten. Erst im Jahre 1971 ging dieser lang
    gehegte Wunsch in Erfüllung.
</p>
<p>
    Insbesondere auf Initiative des damaligen 1. Vorsitzenden Helmut Schmieder,
    wurde am 29. Mai mit dem Bau einer Sporthalle begonnen. Die Halle ist völlig
    in Eigenleistung von den Alvesroder Bürgern erbaut worden und konnte am 26.
    Januar 1974 endlich ihrer Bestimmung übergeben werden. Die Halle wurde von
    insgesamt 115 ehrenamtlichen Helfern in 7803 Arbeitsstunden erbaut.
</p>
<p>
    Durch die Schaffung dieser Sportstätte nahm das Vereinsleben des
    Sportvereins einen großen Aufschwung. Neben Turnen und Gymnastik entwickelte
    sich schon bald das Tischtennisspielen in unserem Dorf zum Volkssport. Neben
    Fußball, Turnen und Tischtennis gibt es seit einigen Jahren auch eine
    Laufsparte sowie eine Bogenschießsparte im Verein.
</p>
<img
    class="rounded float-left mr-2"
    alt=""
    title="Manschaftsfoto &bdquo;Erste Herren&rdquo;"
    src="/public/layout/1_herren15-16gross.jpg"
/>
<p>
    Doch zurück zum Fußball. Im Jahre 1980 wurde neben der Sporthalle ein neuer
    Fußballplatz eingeweiht, auf dem auch heute noch der Spielbetrieb stattfindet.
    Vorbei waren damit die Jahre des legendären Platzes „Vor der Höhe“ mit dem
    unvergessenen alten Bauwagen, der als Umkleideraum diente. 1980 wurde die
    Erste Herren Meister in der 3. Kreisklasse, doch in den Folgejahren musste
    man dann wieder von der 2. Kreisklasse bis hinunter zur 4. Kreisklasse
    absteigen.
</p>
<p>
    1989 wurde dann von den Sportlern unter der Leitung von Klaus Kiehne die
    erste Flutlichtanlage installiert, um zumindest trotz Dunkelheit noch
    vernünftig trainieren zu können. Ob es an der neuen Fluchtlichtanlage lag
    ist nicht überliefert, aber im Jahre 1990 wurde die Mannschaft wieder
    Meister der 4. KK. und stieg somit erneut auf. Im Kreispokal scheiterte man
    erst im Viertelfinale mit einer 2:3 Niederlage gegen den SV Steinkrug. Der
    Durchmarsch in die 2. Kreisklasse 1990/1991 wurde nur knapp verpasst. Hinter
    dem SV Altenhagen belegte man den undankbaren zweiten Tabellenplatz. In den
    nächsten Jahren plätscherte das fußballerische Geschehen so vor sich hin und
    auch einen erneuten Abstieg in die 4. Kreisklasse konnte nicht verhindert
    werden.
</p>
<img
    class="rounded float-right ml-2"
    alt=""
    title="Manschaftsfoto &bdquo;Ü 40&rdquo;"
    src="/public/layout/0001.jpg"
/>
<p>
    In der Saison 1999/2000 war es dann wieder soweit. In einem spannenden, vom
    Kampf beherrschten Spiel wurde am letzten Spieltag durch ein 1:1 in
    Koldingen der langersehnte Wiederaufstieg in die 3. Kreisklasse erreicht.
    „Hunderte“ überwiegend weibliche Fans begleiteten die Truppe ganz in Grün
    gekleidet bei diesem Auftritt. Die Mannschaft wurde bei ihrer Ankunft im Ort
    von den Alvesroder Deistermusikanten empfangen und so ging es im
    Siegestaumel zu Fuß zum Sportplatz. Die Saison 2000/2001 wurde mit dem
    dritten Platz abgeschlossen und man musste in die Relegation um den Aufstieg
    in die 2. Kreisklasse. Doch der Gegner aus Krähenwinkel erwies sich als eine
    Nummer zu groß und man musste sich am Ende mit 4:1 geschlagen geben.
</p>
<p>
    Zwischenzeitlich wurde wiederum in Eigenleistung auf dem Sportplatz neues
    Vereinseigentum geschaffen. Ein ausrangierter Bau-Conainer wurde restauriert
    und als zusätzlicher Sport- u- Geräteraum in die Inventarliste aufgenommen.
    Im Laufe der Zeit entwickelte sich hieraus der „Concorden-Treff“.
</p>
<p>
    Seit dem Jahre 2004 spielt man wieder in der tiefsten Spielklasse. Die Chance
    für den direkten Wiederaufstieg im Jahre 2005 konnte man leider nicht nutzen.
    Im Relegationsspiel um den Aufstieg unterlag man gegen Ronnenberg knapp mit
    0:1. Im Jahre 2006 fusionierte man im Altseniorenbereich mit dem SC Völksen.
    Diese Spielgemeinschaft hatte bis zum Jahre 2015 bestand. Seit der laufenden
    Saison 2015/2016 hat man neben der ERSTEN wieder eine eigene Ü40 Mannschaft
    im Spielbetrieb und im Jugendbereich besteht für die B-Jugend eine
    Spielgemeinschaft mit dem SC Völksen.
</p>
<p>
    Mit Spartenleiter Uwe Blödorn und seinen Stellvertretern Olaf Schalk und
    Volker Bruns ist man bemüht, den Erfolg wieder nach Alvesrode zu bringen.
    Trainer Yavuz Yerli hat ein junges Team zusammengestellt. Die Mannschaft ist
    auf einem guten Weg und hat bereits in der Hinrunde dieser Saison gezeigt,
    dass sie mit jeder Mannschaft mithalten kann.
</p>
<p>
    Das Team freut sich natürlich auch immer über die Unterstützung der Fans an
    der Seitenlinie. Die aktuellen Spieltermine werden regelmäßig auf dieser
    Seite veröffentlicht.

</p>
<div class="modificationDate">
    Stand: <time pubdate="pubdate"><?php echo($this->modificationDate); ?></time>
</div>
