<h1>Wie die Concorden das Laufen lernten…</h1>

<p>
Im März 2013 hat es mit einem lockeren Treffen von laufinteressierten Vereinsmitgliedern
begonnen. Nach Initiative von Uwe Niedergesäß fanden sich mehrere Läufer zusammen,
die fortan nicht mehr alleine ihre Laufrunden ziehen, sondern gemeinsam dem Lauferlebnis
nachgehen wollten.
</p>
<img
    class="rounded float-left mr-2"
    alt=""
    src="/public/layout/t1009.jpg"
/>
<p>
Nach den ersten gemeinsamen Sonntagsläufen war schnell klar, dass dies nicht nur
eine Eintagsfliege war. Nach und nach schlossen sich weitere Laufbegeisterte an,
sodass sich ein fester Läuferstamm bilden konnte.
</p>
<p>
Zeitgleich eröffnete Uwe mit der Durchführung von Anfänger-Gruppen auch Laufanfängern
langsam und behutsam den Laufeinstieg. Er brachte seine Lauferfahrung gekonnt ein,
um den Neulingen den Spaß am Laufen zu vermitteln.
</p>
<p>
Schnell war der Sprung geschafft und die ersten Laufanfänger waren bei den Sonntagsläufen dabei.
</p>
<p>
Die Laufgruppe war zunächst in der Turnsparte des Vereins eingegliedert.
Nachdem schließlich auch an verschiedenen Volksläufen in der Umgebung, u. a.
dem Deister-Marathon in Springe und dem Söltjerlauf im Bad Münder, erfolgreich
teilgenommen wurde, sollte die Laufgruppe nun als eigenständige Sparte im Verein eingerichtet werden.
</p>
<img
    class="rounded float-right ml-2"
    alt=""
    src="/public/layout/t1008.jpg"
/>
<p>
Bei der Jahreshauptversammlung im Januar 2015 wurde durch Beschluss die Laufsparte
gegründet, die fortan durch Dirk Janßen und Marco Syring geleitet wird.
</p>
<p>
Bei dem mittlerweile etablierten „Läufer-Frühstück“ wurden im März 2015 die
neuen Lauftrikots vorgestellt. Bei den künftigen gemeinsamen Ausläufen und bei
Laufveranstaltungen ist die Laufsparte in leuchtend grünen Vereinsfarben zu erkennen.
</p>
<p>
Die Freude am gemeinsamen Lauferlebnis ohne Leistungsdruck hat uns zusammengeführt.
Jeder setzt seine Ziele selber und wer dabei Unterstützung benötigt, dem wird mit
Rat und Tat (Lauf) geholfen.
</p>
<p>
Wer in einer lockeren und zwanglosen Atmosphäre mitlaufen möchte, ist gern gesehen…
</p>
<div class="modificationDate">
    Stand: <time pubdate="pubdate"><?php echo($this->modificationDate); ?></time>
</div>
