<h1>Satzung des VfV Concordia</h1>
<div class="alert alert-dark" role="alert">
    <strong>Anmerkung</strong>
    <p style="margin-bottom: 0">Die aktuelle Fassung steht auch als
    <a
        class="link"
        href="/verein/webseite/download"
    >Download</a>
    zur Verfügung.
    Stand: Juli 2015</p>
    <?php /* FIXME reparierenn
    Stand: <?php echo($this->modiDate->getMonthName()); ?>
    <?php echo($this->modiDate->getYear()); ?>
     */?>

</div>
<h3 id="section1">&#x00A7;1 Zweck des Vereins</h3>
<ol>
    <li>

        Zweck des Vereins ist die Förderung und Pflege der Sportausübung
        allgemein und insbesondere in den Bereichen Fußball, Turnen,
        Tischtennis, Bogenschießen, Laufen sowie in anderen durch Beschluss der
        Mitgliederversammlung aufgenommenen Sparten.
    </li>
    <li>
        Der Verein ist Mitglied des Landessportbundes Niedersachsen e.V.
        mit seinen Gliederungen sowie der Fachverbände für die vom Verein
        betriebenen Sparten.
    </li>
    <li>
        Der Verein ist politisch, konfessionell und rassisch neutral.
    </li>
    <li>
        Der Verein verfolgt ausschließlich und unmittelbar gemeinnützige
        Zwecke im Sinne des Abschnitts &quot;Steuerbegünstigte Zwecke&quot;
        der Abgabenordnung (&#x00A7;&#x00A7; 51-68 AO). Er ist selbstlos
        tätig und darf nicht auf Gewinnerzielung abgestellt sein.
    </li>
    <li>
        Mittel des Vereins dürfen nur für die satzungsmäßigen Zwecke
        verwendet werden. Die Mitglieder erhalten in ihrer Eigenschaft
        als Mitglied keine Zuwendungen aus Mitteln des Vereins. Es dürfen
        keine Personen durch Ausgaben, die dem Zweck des Vereins fremd sind
        oder durch unverhältnismäßig hohe Vergütungen begünstigt werden.
    </li>
</ol>

<h3 id="section2">&#x00A7;2 Name, Sitz, Geschäftsjahr</h3>
<ol>
    <li>
        Der Verein führt den Namen VfV Concordia Alvesrode von 1919 e. V.
        und hat seinen Sitz im Ortsteil Alvesrode der Stadt Springe.
    </li>
    <li>
        Das Geschäftsjahr des Vereins ist das Kalenderjahr
    </li>
</ol>
<h3 id="section3">&#x00A7;3 Gliederung des Vereins</h3>
<ol>
    <li>
        Der Verein gliedert sich in Sparten, die jeweils eine bestimmte
        Sportart betreiben.
    </li>
    <li>
        Die Sparten können sich in Unterabteilungen gliedern, und zwar je
        nach Bedarf in
        <ol>
            <li>Kinderabteilungen für Kinder bis 14 Jahre</li>
            <li>Jugendabteilungen für Jugendliche zwischen 14 und 18 Jahren</li>
            <li>Seniorenabteilungen für Erwachsene</li>
        </ol>
    </li>
</ol>
<h3 id="section4">&#x00A7;4 Mitgliedschaft</h3>
<ol>
    <li>Mitglied des Vereins kann jede Person werden, die eine im Verein angebotene Sportart betreiben oder die Zwecke des Vereins fördern will. Eine Aufnahmegebühr wird nicht erhoben.</li>
    <li>Der Verein besteht aus ordentlichen Mitgliedern, jugendlichen Mitgliedern, passiven Mitgliedern und Ehrenmitgliedern.
        <ol>
            <li>Ordentliche Mitglieder sind aktive Mitglieder, die an sportlichen Veranstaltungen aktiv teilnehmen und die am 1.1. des laufenden  Geschäftsjahres das 18. Lebensjahr vollendet haben.</li>
            <li>Jugendliche Mitglieder sind aktive Mitglieder, die am 1.1. des laufenden Geschäftsjahres das 18. Lebensjahr noch nicht vollendet haben.</li>
            <li>Passive Mitglieder sind Mitglieder, die sich selbst nicht sportlich betätigen, aber im Übrigen die Interessen des Vereins fördern.</li>
            <li>Personen, die sich in besonderem Maße Verdienste für den Verein erworben haben, können durch Beschluss der Mitgliederversammlung zu Ehrenmitgliedern ernannt werden. Sie haben die Rechte der ordentlichen Mitglieder und sind von der Beitragsleistung befreit.</li>
        </ol>
    </li>
</ol>
<h3 id="section5">&#x00A7;5 Rechte und Pflichten der Mitglieder</h3>
<ol>
    <li>Alle Mitglieder haben das Recht, dem Vorstand und der Mitgliederversammlung Anträge zu unterbreiten. Sie sind berechtigt, an allen Veranstaltungen des Vereins teilzunehmen und die Einrichtungen des Vereins nach Maßgabe der hierfür getroffenen Bestimmungen zu benutzen.</li>
    <li>Das Stimmrecht in der Mitgliederversammlung steht den ordentlichen, den passiven und den Ehrenmitgliedern zu. Eine  Stimmrechtsübertragung ist nicht zulässig.</li>
    <li>Die Mitglieder sind verpflichtet,
        <ol>
            <li>die Ziele des Vereins nach besten Kräften zu fördern</li>
            <li>den Beitrag rechtzeitig zu entrichten</li>
            <li>Vereinseigentum schonend zu behandeln.</li>
        </ol>
    </li>
</ol>

<h3 id="section6">&#x00A7;6 Beginn und Ende der Mitgliedschaft</h3>
<ol>
    <li>Eine Mitgliedschaft entsteht mit der Annahme eines schriftlich zu stellenden Aufnahmeantrages durch Beschluss des
    Vorstandes. Wird die Aufnahme abgelehnt, steht dem Aufnahmesuchenden Berufung an die nächste Mitgliederversammlung zu, die endgültig entscheidet.</li>
    <li>Die Mitgliedschaft endet
        <ol>
            <li>durch den Tod</li>
            <li>durch Austritt</li>
            <li>durch Ausschluss</li>
        </ol>
    </li>
    <li>Austritt erfolgt auf Grund einer schriftlichen Erklärung unter Einhaltung einer Kündigungsfrist von einem Monat jeweils zum Schluss eines Kalenderhalbjahres.</li>
    <li>Ausschluss erfolgt
        <ol>
            <li>bei grobem oder wiederholtem Verstoß gegen die Satzung oder gegen die Interessen des Vereins.</li>
            <li>wegen groben unsportlichen oder unkameradschaftlichen Verhaltens</li>
            <li>wegen unehrenhaften Verhaltens innerhalb oder außerhalb des Vereinslebens.</li>
        </ol>
    </li>
    <li>
        <p>Über den Ausschluss entscheidet der Vorstand mit 3/4 Mehrheit. Der Auschluss erfolgt mit sofortiger Wirkung.</p>
        <p>Vor Entscheidung des Vorstandes ist dem Mitglied unter Setzung einer Frist von mindestens zwei Wochen Gelegenheit zu geben, sich zu den erhobenen Vorwürfen zu äußern.</p>
        <p>Der Ausschließungsbeschluss ist dem Mitglied unter eingehender Darlegung der Gründe durch eingeschriebenen Brief bekanntzugeben. Gegen diesen Beschluss ist die Berrufung zur Mitgliederversammlung statthaft.</p>
        <p>Die Berufung muss innerhalb einer Frist von zwei Wochne nach Zugang des Ausschließungsbeschluss beim Vorstand schriftlich eingelegt werden. Wird der Ausschließungsbeschluss nicht fristgerecht angefochten, so wird dieser formell verbindlich.</p>
    </li>
    <li>Mit Beendigung der Mitgliedschaft erlöschen alle Ansprüche aus dem Mitgliedverhältnis, unbeschadet des Anspruches des Vereins auf rückständige Beitragsforderungen und Rückgabe von Vereinseigentum.</li>
</ol>
<h3 id="section7">&#x00A7;7 Jahresbeitrag</h3>
<ol>
    <li>Der Verein erhebt einen Jahresbeitrag. Die Höhe des Betrages wird durch die Mitgliederversammlung festgesetzt.</li>
    <li>Der Beitrag ist auch dann für ein Halbjahr zu zahlen, wenn ein Mitglied während des Jahres ausritt, ausgeschlossen wird oder erst während des Geschäftsjahres eintritt.</li>
    <li>Der Beitrag kann halbjährlich gezahlt werden und ist jeweils im Voraus zu entrichten.</li>
    <li>Der Vorstand hat das Recht, bei Bedürftigkeit eines Mitgliedes Jahresbeiträge zu stunden, ganz oder teilweise zu erlassen.</li>
    <li>über Änderungen der Jahresbeiträge entscheidet die Mitgliederversammlung.</li>
    <li>Sonderspartenbeiträge können erhoben werden.</li>
</ol>

<h3 id="section8">&#x00A7;8 Organe des Vereins</h3>
Organe des Vereins sind
<ol>
    <li>der Vorstand</li>
    <li>die Mitgliederversammlung.</li>
</ol>

<h3 id="section9">&#x00A7;9 Der Vorstand</h3>
<ol>
    <li>Der Vorstand gem. &#x00A7;26 BGB besteht aus
        <ol>
            <li>dem 1. Vorsitzenden</li>
            <li>dem 2. Vorsitzenden</li>
            <li>dem Kassenwart</li>
            <li>dem Schriftführer</li>
        </ol>
    </li>
    <li>
        <p>Die Mitgliederversammlung wählt den Vorstand auf 2 Jahre. Wiederwahl ist unbegrenzt zulässig.</p>
        <p>Der Verein wird jeweils durch zwei Vorstandsmitglieder gerichtlich und außergerichtlich vertreten.</p>
        <p>Zahlungsanweisungen bedürfen der Unterschrift des Kassenwartes und des 1. Vorsitzenden oder bei dessen Verhinderung des 2.Vorsitzenden.</p>
        <p>Zahlungsanweisungen unter 1000 Euro können vom Kassenwart oder dem 1. Vorsitzenden oder bei dessen Verhinderung vom 2. Vorsitzenden allein getätigt werden.</p>
    </li>
    <li>
        Dem Vorstand obliegt die Verwaltung des Vereinsvermögens und die Ausführung der Vereinsbeschlüsse. Er führt die laufenden Geschäfte des Vereins.
    </li>
    <li>
        <p>Der Vorstand fasst seine Beschlüsse in Vorstandssitzungen, die vom 1. Vorsitzenden und bei dessen Verhinderung vom 2. Vorsitzenden einberufen werden.</p>
        <p>Der Vorstand ist beschlussfähig, wenn mindestens 3 Vorstandsmitglieder anwesend sind.</p>
        <p>Bei Beschlussunfähigkeit muss binnen zwei Wochen eine 2. Sitzung mit derselben Tagesordnung einberufen werden. Diese ist ohne Rücksicht auf die Zahl der erschienenen Vorstandsmitglieder beschlussfähig.</p>
        <p>Beschlüsse werden mit einfacher Stimmenmehrheit gefasst. Bei Stimmengleichheit entscheidet die Stimme des Sitzungsleiters.</p>
    </li>
    <li>
        Bei Ausscheiden eines Vorstandsmitgliedes haben die übrigen Vorstandsmitglieder das Recht, einen Ersatzmann bis zur Mitgliederversammlung zu bestellen.
    </li>
    <li>
        <p>Der 1. Vorsitzende nimmt die Geschäfte des Vereins nach den Vorschriften der Satzung und den auf den Mitgliederversammlungen gefassten Beschlüsse wahr. Er kann innerhalb eines Geschäftsjahres 250 Euro ohne vorherige Genehmigung des Vorstandes für Vereinszwecke ausgeben. Die Unterrichtung des Vorstandes ist bei einer Vorstandssitzung, bei der der Kassenwart als Vorstandsmitglied anwesend sein muss, sobald wie möglich nachzuholen.</p>
        <p>Der 1. Vorsitzende hat dem Vorstand von allen wichtigen Vereinsangelegenheiten sofort Kenntnis zu geben.</p>
        <p>Der 2. Vorsitzende vertritt den 1. Vorsitzenden bei der Wahrnehmung dieser Geschäfte im Verhinderungsfall und unterstützt ihn.</p>
        <p>Der Kassenwart verwaltet die Gelder des Vereins. Er hat der Mitgliederversammlung eine Jahresabrechnung vorzulegen. Er kann beantragen, innerhalb von 4 Wochen eine Mitgliederversammlung einzuberufen.</p>
        <p>Der Schriftführer führt Protokoll bei sämtlichen Mitgliederversammlungen und Vorstandssitzungen.</p>
    </li>
</ol>
<h3 id="section10">&#x00A7;10 Die Mitgliederversammlung</h3>
<ol>
    <li>Die Mitgliederversammlung ist einmal jährlich durch den Vorstand einzuberufen.</li>
    <li>Die Mitglieder sind unter Bekanntgabe der Tagesordnung und unter Einhaltung einer Frist von mindestens zwei Wochen schriftlich einzuladen.</li>
    <li>
        <p>Der Vorstand kann auch jederzeit eine außerordentliche Mitgliederversammlung einberufen.</p>
        <p> Hierzu ist er verpflichtet, wenn ein Drittel der stimmberechtigten Mitglieder dies unter Angabe des Zwecks und der Gründe schriftlich verlangt. Die Mitglieder sind in diesem Fall analog Abs. 2 einzuladen.</p>
    </li>
    <li>
        <p>Zur Beschlussfassung ist die Mehrheit der erschienenen, stimmberechtigten Mitglieder notwendig.</p>
        <p>Wenn ein Viertel der erschienenen, stimmberechtigten Mitglieder es verlangt, ist eine Abstimmung geheim vorzunehmen.</p>
    </li>
    <li>Die Mitgliederversammlung hat insbesondere folgende Aufgaben:
        <ol>
            <li>die Wahl des Vorstandes auf die Dauer von zwei Jahren.</li>
            <li>die Wahl von drei Kassenprüfern auf die Dauer von zwei Jahren. Einmalige Wiederwahl ist möglich.</li>
            <li>die Entlastung des Vorstandes nach Entgegennahme des Jahres- und Kassenberichtes und des Prüfberichtes der Kassenprüfer.</li>
            <li>die Beschlussfassung über Satzungsänderungen und alle sonstigen ihr vom Vorstand unterbreiteten Aufgaben oder nach der Satzung übertragenen Angelegenheiten.</li>
            <li>Beschlussfassung über die Auflösung des Vereins.</li>
        </ol>
    </li>
    <li>Den Vorsitz in der Mitgliederversammlung führt der 1. Vorsitzende, bei seiner Verhinderung der 2. Vorsitzende.</li>
    <li>Die Mitgliederversammlung fasst Beschlüsse mit einfacher Stimmenmehrheit; es sei denn, die Satzung schreibt eine andere Stimmenmehrheit vor.</li>
</ol>

<h3 id="section11">&#x00A7;11 Beurkundung von Beschlüssen; Niederschriften</h3>
<ol>
    <li>
        Die Beschlüsse des Vorstandes und der Mitgliederversammlung sind
        schriftlich abzufassen und vom jeweiligen Sitzungsleiter und dem
        Schriftführer zu unterzeichnen.
    </li>
    <li>
        Über jede Mitgliederversammlung wird eine Niederschrift aufgenommen,
        die vom Versammlungsleiter und vom Schriftführer zu unterzeichnen
        ist.
    </li>
    <li>
        Bei Verhinderung des Schriftführers wird die Funktion des
        Schriftführers durch ein vom Sitzungsleiter zu bestimmendes anderes Vorstandsmitglied wahrgenommen.</li>
</ol>
<h3 id="section12">&#x00A7;12 Satzungsänderung</h3>
<ol>
    <li>
        Eine Änderung der Satzung kann nur durch Beschluss der Mitgliederversammlung
        erfolgen, wobei eine Mehrheit von drei Viertel der abgegebenen Stimmen der
        anwesenden, stimmberechtigten Mitglieder erforderlich ist.
    </li>
</ol>
<h3 id="section13">&#x00A7;13 Vermögen</h3>
<ol>
    <li>
        Alle Beiträge, Einnahmen und Mittel des Vereins werden
        ausschließlich zur Erreichung des Vereinszweckes verwendet.
    </li>
    <li>
        Im Falle der Auflösung des Vereins oder bei Wegfall
        steuerbegünstigter Zwecke fällt das vorhandene Vereinsvermögen nach
        Abdeckung möglicher Verbindlichkeiten an den Gesangverein Frohsinn
        Alvesrode e. V., sofern dieser existent ist, anderenfalls an die
        Stadt Springe - OT Alvesrode- zu gemeinnützigen Zwecken zu.
    </li>
</ol>
<h3 id="section14">&#x00A7;14 Vereinsauflösung</h3>
<ol>
    <li>
        Die Auflösung des Vereins erfolgt durch Beschluss der
        Mitgliederversammlung, wobei drei Viertel der abgegebenen Stimmen
        für die Auflösung stimmen und mindestens 75% aller stimmberechtigten
        Mitglieder anwesend sein müssen.
    </li>
    <li>
        Die Mitgliederversammlung ernennt zur Abwicklung der Geschäfte drei
        Liquidatoren.
    </li>
</ol>
<div class="modificationDate">
    Stand: <time pubdate="pubdate"><?php echo($this->modificationDate); ?></time>
</div>
