<h1>Helmut Schmieder</h1>
<h3>12. Juni 1939 - 15. Mai 1977</h3>
<img
    class="rounded float-left mr-2"
    alt=""
    src="/public/layout/schmieder.jpg"
/>
<p class="pull-xs-right">
    Helmut Schmieder spielte seit 1960 Fußball beim VfV Concordia Alvesrode.
    1966 wurde er zum 1. Vorsitzenden des Vereins gewählt, nachdem er sich
    bereits als Jugendleiter bewährt hatte.
</p>
<p>
    In Würdigung seiner Verdienste und seines unermüdlichen Eintretens für seine
    Ziele wurde Helmut Schmieder 1974 vom NFV Kreis Springe die silberne
    Ehrennadel verliehen.
</p>
<p>
    Nachdem er schon den Bau von Duschanlagen für die Spieler vorangetrieben
    hatte und die Installation einer Flutlichtanlage organisierte, gelang es
    ihm 1971, den Gemeinderat von der Notwendigkeit des Baus einer
    Mehrzweckhalle in Alvesrode zu überzeugen.
</p>
<p>
    Ohne Eigenleistung konnte jedoch ein solches Vorhaben bei den vorhandenen
    geringen finanziellen Mitteln nicht durchgeführt werden. Letztendlich
    kostete der Bau der Halle 360.000 DM. Durch Spenden von Alvesroder
    Bürgerinnen und Bürgern sowie Zuschüssen vom Landkreis und Kreissportbund
    konnte im Jahr 1974 die neue Halle eingeweiht werden.
</p>
<p>
    Dass Alvesrode heute über eine Mehrzweckhalle und einen
    Dorfgemeinschaftsraum verfügen kann und dass der Sportverein seitdem eine
    bedeutende Zunahme an aktiven Mitgliedern sowie die Gründung neuer Sparten
    aufweisen kann, ist der Verdienst Helmut Schmieders.
</p>
<div class="modificationDate">
    Stand: <time pubdate="pubdate"><?php echo($this->modificationDate); ?></time>
</div>
