<h1>Termine und Trainingszeiten</h1>
<div>
    <h4>Termine </h4>
    Folgende Termine liegen an:
    <div class="reload-content" data-url="/fussball/sparte/termine/termine" />
</div>
<div>
    <h4>Trainingszeiten</h4>
    Die Gruppen treffen sich zu folgenden Zeiten:
    <div class="reload-content" data-url="/fussball/sparte/termine/trainingszeiten" />
</div>
<div>
    <?php if(isset($this->addContent)): ?>
    <?php echo($this->addContent); ?>
    <?php endif; ?>
</div>
<p>
    In allen Gruppen sind jederzeit neue Mitglieder willkommen.
</p>
<div class="alert alert-dark" role="alert">
    <strong>Anmerkung</strong>
    <p style="margin-bottom: 0">
    Nicht-Vereinsmitglieder sind jederzeit zu Probestunden eingeladen,
    sind dann jedoch <i><u><strong>nicht</strong></u></i> über den Sportverein unfallversichert.
    </p>
</div>
<p>
    <?php if($this->addInfo): ?>
    Zusätzlich zum Vereinsbeitrag wird bei der Bogensparte auch für bereits
    bestehende Mitgliedschaften im Verein ein Spartenbeitrag erhoben.
    Dieser beträgt für Erwachsene 30,00 € und für Jugendliche bis zum
    18. Lebensjahr 20,00 € jährlich.
    <?php else: ?>
    Für Vereinsmitglieder ist die Teilnahme an allen Gruppen ohne zusätzliche
    Spartenbeiträge möglich.
    <?php endif; ?>
</p>
<div class="alert alert-dark" role="alert">
    <strong>Anmerkung</strong>
    <p style="margin-bottom: 0">
    In den Schulferien findet mit vorheriger Bekanntgabe teilweise kein Training statt!
    </p>
</div>
<div class="modificationDate">
    Stand: <time pubdate="pubdate"><?php echo($this->modificationDate); ?></time>
</div>
