<h1>Wissenswertes über die Sparte Tischtennis</h1>
<img
    class="rounded float-left mr-2"
    alt=""
    src="/public/layout/t1007.jpg"
/>
<p>
    Nach Fertigstellung der Helmut-Schmieder-Halle im Jahre 1974 hat sich der Tischtennissport in Alvesrode etabliert.
    Verantwortlich für den Aufbau zeigten sich Brunhilde Blume, Karlfried Weber und Werner Bente.
</p>
<p>
    Nach ersten Trainingsfortschritten kam es mit Beginn der Saison 1975/76 zur Anmeldung der ersten 3 Mannschaften zum
    Punktspielbetrieb auf Kreisebene. 1979 gelang der 1. Damenmannschaft der Aufstieg in die Bezirksklasse.
    Im Herrenbereich dauerte es 10 Jahre länger.
</p>
<p>
    Den Aufstieg in die Bezirksebene konnte man 1989 feiern. Nunmehr seit 20 Jahren ist der Verein sowohl im Damen-
    als auch Herrenbereich auf Bezirksebene vertreten. Dies hat im Gebiet der Stadt Springe ebenfalls nur der
    TTC Völksen seit der Saison 2007/08 erreicht.
</p>
<div class="modificationDate">
    Stand: <time pubdate="pubdate"><?php echo($this->modificationDate); ?></time>
</div>