<h1>35 Jahre Turnen und Gymnastik in Alvesrode</h1>
<p>
    Die Turnsparte des Sportvereins VfV Concordia Alvesrode wurde Ende 1973 nach Fertigstellung der Helmut-Schmieder-
    Halle gegründet. Zunächst startete der Verein mit einer Damen- und zwei Kindergruppen.
    Einige Jahre später wurde dann das Sportangebot durch eine eigene Turngruppe für die Jungen sowie die Jedermanngruppe und die
    Jazzgymnastik ergänzt. In den 1980er-Jahren kam die Aerobic-Welle aus Amerika auch in Alvesrode an, die
    ersten jungen Frauen schwitzten zu flotter Musik.
</p>
<img
    class="rounded float-left mr-2"
    alt=""
    src="/public/layout/t1005.jpg"
/>
<p>
    Im Laufe der Jahre wechselte das Interesse der Sportler und die Turnsparte hat sich bemüht, entsprechende
    Angebote anzubieten. Anstelle der Jazzgymnastik wurden Wirbelsäulengymnastik und kurzzeitig auch Walking-
    Einführungskurse angeboten. Leider war es dem Verein nicht möglich, diese Angebote dauerhaft ohne zusätzliche
    Kostenbeiträge der Teilnehmer anzubieten.
</p>

<p>
Die jungen Frauen wurden älter und aus Aerobic wurde Bauch-Beine-Po-Gymnastik.
In dieser Gruppe sowie auch bei der Damengymnastik werden auch Übungen der Wirbelsäulengymnastik durchgeführt.
Dehnübungen und eine kurze Entspannungsphase zum Ende der Stunde runden das Programm ab.
Die zwischendurch sehr stark reduzierte Teilnehmerzahl konnte nicht zuletzt durch einige junge Mädchen ab ca. 14 Jahren wieder
auf ca. 10 - 15 Sportlerinnen gesteigert werden.
</p>
<img
    class="rounded float-right ml-2"
    alt=""
    src="/public/layout/t1004.jpg"
/>
<p>
Die Damen-Gymnastikgruppe besteht aus Frauen vom jungen Erwachsenenalter bis zum Rentenalter, die sich gemeinsam
fit halten. Viele der ca. 10 - 15 regelmäßigen Teilnehmerinnen kommen auch aus Völksen.
</p>
<p>
Den Abschluss des Montagabends bilden unsere Männer, die in einer kleinen Gruppe gemeinsam turnen und sich bei Ballspielen
auspowern.
</p>

<p>
Beim Kinderturnen hinterlässt leider der dauerhafte Geburtenrückgang seine Spuren. Nachdem im letzten Jahr bereits die Mutter-
Kind-Turngruppe mit der Kindergartenkinder-Turngruppe zusammengelegt wurde, sind im Jahr 2009 die letzten beiden
verbliebenen Turnkinder im Kindergartenalter vorzeitig in die Gruppe der Grundschulkinder gewechselt, so dass jetzt
nur noch eine Kinderturngruppe angeboten wird. Bei entsprechender Nachfrage wird das Angebot wieder erweitert.
Ein großer Erfolg ist hingegen die Mädchengruppe, die sich speziell im Geräteturnen übt.
</p>

<p>
Auf Wunsch der Mädchen und Jungen ab ca. 10 Jahren wird in dieser Altersklasse nicht mehr geturnt sondern die
Jugendlichen treffen sich regelmäßig zu Ballspielen.
</p>
<img
    class="rounded float-left mr-2"
    alt=""
    src="/public/layout/t1006.jpg"
/>
<p>
Aus der Jedermann-Turngruppe ist eine Gruppe für Jungen ab ca. 14 Jahren und junge männliche Erwachsene geworden. Diese Gruppe wird
bereits seit Jahren von Hennig Flügge geleitet.
</p>

<p>
In all den Jahren wechselten auch die Übungsleiter immer mal wieder, so sollte jedoch an dieser Stelle erwähnt werden, dass Renate Herwig
seit vielen Jahren die verschiedenen Turngruppen leitet. Aus beruflichen Gründen konnte sie die Kindergruppen nicht mehr betreuen.
</p>

<p>
Diese Aufgabe hat zunächst Angelina Buchholz mit Unterstützung durch Isabell Twick über- nommen. Seit einem Jahr turnen
Wiebke Maticka und Margo Blödorn mit den Kindern.
</p>
<div class="modificationDate">
    Stand: <time pubdate="pubdate"><?php echo($this->modificationDate); ?></time>
</div>