<h1>90 Jahre VfV&nbsp;Concordia</h1>
<p>
    Am 4. Juni 1919 wurde der Sportverein "Concordia Alvesrode" als reiner
    Fußballverein gegründet. In den folgenden Wochen wurde sich bemüht, eine
    Rasenfläche zu pachten, um Fußball und Schlagball spielen und auch
    Freiübungen abhalten zu können. Dieses gelang auch; eine Fläche von 75x120
    Meter konnte vom Hofbesitzer L. Flügge für 180 Mark Pacht erworben werden.
    Somit waren die Grundsteine gelegt um an einem geregelten Spielbetrieb
    teilzunehmen.
</p>
<img
    class="rounded float-left mr-2"
    alt=""
    src="/public/layout/1003.png"
/>
<p>
    In den Jahren 1923 - 1928 kam der Spielbetrieb aufgrund der wirtschaftlichen
    Schwierigkeiten zum Erliegen, bis sich 1928 wieder eine schlagkräftige
    Truppe von jungen Männern zusammen fand, um so, wie man sich erzählt, den
    Gegnern das Fürchten zu lehren.
    <br />
    <br />
    Durch die Auswirkungen des Zweiten Weltkrieges war natürlich an sportliche
    Betätigung nicht zu denken, bevor sich 1945 erneut eine Gruppe junger Männer
    zusammenschloss um Fußball zu spielen. Der damalige Vorsitzende war Willi
    Weber sen.
</p>
<p>
    In den folgenden Jahren spielten in Alvesrode verschiedene Herren-/ und
    Jugendmannschaften. Obwohl im Laufe der Jahre wiederholte Versuche gestartet
    wurden auch andere Sportarten als Fußball in Alvesrode zu betreiben,
    scheiterte dies stets an den fehlenden Übungsmöglichkeiten. Dieses änderte
    sich erst 1971.
</p>
<p>
    Zwei Jahre nach dem 50 jährigen Vereinsjubiläum ging ein lang gehegter
    Wunsch in Erfüllung. Am 29. Mai 1971 wurde mit dem Bau einer Sporthalle
    begonnen. Die Halle wurde völlig in Eigenleistung von Alvesrodern erbaut
    und konnte am 26. Januar 1974 ihrer Bestimmung übergeben werden. Hierbei
    wurden von 115 ehrenamtlichen Helfern insgesamt 7.803 Arbeitsstunden
    geleistet.
</p>
<p>
    Durch die Schaffung der Sportstätte, für die an dieser Stelle dem damaligen
    1. Vorsitzenden Helmut Schmieder als Initiator so wie allen Helfern
    besonderer Dank gebührt, nahm das Vereinsleben in Alvesrode, und hier
    insbesondere auch im Sportverein, einen ungeahnten Aufschwung.
</p>
<img
    class="rounded float-right ml-2"
    alt=""
    src="/public/layout/1004.png"
    title="Die Gründer der Tischtennissparte (v.l.n.r): Karlfred Weber, Brunhilde Blume, Werner Bente"
/>
<p>
    Neben Turnen und Gymnastik für Jung und Alt, entwickelte sich das
    Tischtennis-spielen in unserem Dorf zum "Volkssport". Hier werden bis heute
    noch höchste sportliche Erfolge erzielt. Im Jahre 1974 stieg die
    Mitgliederzahl auf 319, bei einer Einwohnerzahl von 550.
</p>
<p>
    1978 erlitt der Verein durch den Tod des langjährigen Vorsitzenden Helmut
    Schmieder einen schweren Verlust. Er hinterließ eine kaum zu schließende
    Lücke. Die in seiner Ära erbaute Turnhalle erhielt ihm zu Ehren den Namen
    "Helmut-Schmieder-Halle".
</p>
<p>
    Nun fehlte uns nur noch ein eigener Sportplatz, der 1980 neben der
    Helmut-Schmieder-Halle eingeweiht wurde und auf dem heute noch der
    Spielbetrieb stattfindet. Wie überall ist dieser Sport mit Höhen und Tiefen
    versehen. Mal steigt man auf und mal ab.
</p>
<p>
    Zu dem hat sich auf dem Gelände viel getan. Es wurden zwei Container
    aufgestellt, die als Geräteraum und als Vereinsheim genutzt werden. So war
    es nur eine Frage der Zeit, bis einige Vereinsmitglieder sich an die Arbeit
    machten, um eine Grillhütte und eine Überdachung anzubauen. Damit entstand
    ein Platz, an den man sich gerne trifft und feiert.
</p>
<p>
    Heute können wir mit 302 Mitgliedern auf eine lange und gute Entwicklung
    zurückblicken. Es wird
    <br />
    in Alvesrode immer noch Fußball und Tischtennis gespielt und für Jung und
    Alt Turnen und
    <br />
    Gymnastik angeboten, obwohl das Angebot an Freizeitbeschäftigungen immer
    größer wird. Doch diesen Kampf wollen wir gerne annehmen, solange es in
    unserem Verein Mitglieder gibt, die Aufgaben, die sie gestellt bekommen,
    mit so viel Engagement, Freude und sportlicher Disziplin durchführen. Denn
    dieses ist die Basis eines intakten Vereins. Sorgen macht der Mangel an
    Nachwuchs, der sich in unseren Jugendbereichen einschleicht. Denn die
    Jugend von heute ist die Zukunft von morgen.
</p>
<div class="modificationDate">
    Stand: <time pubdate="pubdate"><?php echo($this->modificationDate); ?></time>
</div>


